-- Create Database
CREATE DATABASE ZomatoDB;
USE ZomatoDB;

-------------------------------------------------------------
-- Task 2: Perform Simple Data Transformations Using SQL
-------------------------------------------------------------

----------------------------
-- Basic Data Cleaning
----------------------------
-- a.Remove duplicate records. 

SELECT * FROM 
( SELECT o.*, ROW_NUMBER() OVER (PARTITION BY order_id, restaurant_id, customer_id, order_date, order_time, delivery_time, total_cost, item_count, payment_method, customer_rating 
ORDER BY order_date DESC, order_time DESC) rn FROM Zomato_Orders o ) t 
WHERE rn> 1; 
-- no duplicates 
SELECT * FROM Zomato_Restaurants; 
SELECT * FROM 
( SELECT r.*, ROW_NUMBER() OVER (PARTITION BY restaurant_id, restaurant_name, city, area, cuisine, avg_rating, total_ratings, price_range, delivery_available 
ORDER BY restaurant_id DESC) rn FROM Zomato_Restaurants r ) t WHERE rn> 1; 
-- no duplicates

-- b.Handle NULL values (if any) by replacing them with appropriate values.

SELECT *
FROM Zomato_Restaurants
WHERE restaurant_id IS NULL
   OR restaurant_name IS NULL
   OR city IS NULL
   OR area IS NULL
   OR cuisine IS NULL
   OR avg_rating IS NULL
   OR total_ratings IS NULL
   OR price_range IS NULL
   OR delivery_available IS NULL;
-- NO NULL 
SELECT *
FROM Zomato_Orders
WHERE order_id IS NULL
   OR restaurant_id IS NULL
   OR customer_id IS NULL
   OR order_date IS NULL
   OR order_time IS NULL
   OR delivery_time IS NULL
   OR total_cost IS NULL
   OR item_count IS NULL
   OR payment_method IS NULL
   OR customer_rating IS NULL;
 -- NO NULL   
 
----------------------------
-- Data Exploration Queries
----------------------------
-- Count the number of restaurants in each city.
select city,count(restaurant_name)
from Zomato_restaurants
group by city;

-- Find the top 5 cities with the highest number of orders.
select r.city,count(o.order_id) as cnt
from Zomato_restaurants r
join Zomato_Orders o on o.restaurant_id=r.restaurant_id
group by city 
order by cnt desc
limit 5;

-- Calculate the total revenue generated by each restaurant.
select r.restaurant_name, sum(o.total_cost) as revenue
from Zomato_restaurants r
join Zomato_Orders o on o.restaurant_id=r.restaurant_id
group by restaurant_name
order by revenue desc;

----------------------------
-- Data Aggregation
----------------------------

-- Find the average order amount for each city.
select r.city, avg(o.total_cost) as average
from Zomato_restaurants r
join Zomato_Orders o on o.restaurant_id=r.restaurant_id
group by city order by average desc;

-- Identify the top 5 restaurants with the highest total sales.
select r.restaurant_name, sum(o.total_cost) as highest_total_sales
from Zomato_restaurants r
join Zomato_Orders o on o.restaurant_id=r.restaurant_id
group by restaurant_name 
order by highest_total_sales desc
limit 5;

----------------------------
-- Data Joins
----------------------------

-- Join the Zomato_Orders and Zomato_Restaurants tables to get restaurant names along with order details.
CREATE TABLE Zomato_restaurants_orders AS
SELECT 
    o.order_id, o.customer_id, o.order_date, o.order_time, o.delivery_time, o.total_cost,
    o.item_count, o.payment_method, o.customer_rating, r.restaurant_id, r.restaurant_name,
    r.city, r.area, r.cuisine, r.avg_rating, r.total_ratings, r.price_range, r.delivery_available
FROM Zomato_Orders o
JOIN Zomato_Restaurants r
ON o.restaurant_id = r.restaurant_id;

select * from Zomato_restaurants_orders limit 5;


